# Generated by Django 5.2.1 on 2025-07-19 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrefectureModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="県名",
                    ),
                ),
                ("region", models.CharField(max_length=3, verbose_name="地域")),
            ],
            options={
                "db_table": "prefecture_master",
                "indexes": [
                    models.Index(fields=["name"], name="prefecture__name_8fc51c_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="顧客ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="氏名")),
                (
                    "registration_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                ("kana", models.CharField(max_length=20, verbose_name="氏名カナ")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="メールアドレス"),
                ),
                ("sex", models.CharField(max_length=1, verbose_name="性別")),
                ("age", models.IntegerField(verbose_name="年齢")),
                ("birthday", models.DateField(verbose_name="誕生日")),
                (
                    "prefecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ecSiteAnalysis.prefecturemodel",
                        verbose_name="都道府県",
                    ),
                ),
            ],
            options={
                "db_table": "customer_master",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("age__gt", 0)),
                        name="constraint_age_greater_than_zero",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("age__lte", 100)),
                        name="constraint_age_less_than_or_equal_100",
                    ),
                ],
            },
        ),
    ]
