# Generated by Django 5.2.1 on 2025-07-21 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecSiteAnalysis", "0001_table_recreate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseSummaryModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="購入金額")),
                ("payment_datetime", models.DateTimeField(verbose_name="購入日時")),
                (
                    "customer_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ecSiteAnalysis.customermodel",
                        verbose_name="顧客ID",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_summary",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gt", 0)),
                        name="constraint_price_greater_than_zero",
                    )
                ],
            },
        ),
    ]
