# Generated by Django 5.2.1 on 2025-07-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecSiteAnalysis", "0002_append_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="商品ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="商品名")),
                ("price", models.IntegerField(verbose_name="価格")),
            ],
            options={
                "db_table": "item_master",
                "indexes": [
                    models.Index(fields=["name"], name="item_master_name_332e20_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gt", 0)),
                        name="constraint_item_price_greater_than_zero",
                    )
                ],
            },
        ),
    ]
