# Generated by Django 5.2.1 on 2025-07-21 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecSiteAnalysis", "0003_append_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseDetailModel",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="購入詳細ID"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "item_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ecSiteAnalysis.itemmodel",
                        verbose_name="購入商品ID",
                    ),
                ),
                (
                    "purchase_summary_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecSiteAnalysis.purchasesummarymodel",
                        verbose_name="購入明細ID",
                    ),
                ),
            ],
            options={
                "db_table": "purchase_detail",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="constraint_wuantity_greater_than_zero",
                    )
                ],
            },
        ),
    ]
