# Generated by Django 5.2.1 on 2025-07-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecSiteAnalysis", "0004_append_mode"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="purchasedetailmodel",
            name="constraint_wuantity_greater_than_zero",
        ),
        migrations.AddConstraint(
            model_name="purchasedetailmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="constraint_wuantity_greater_than_zero",
            ),
        ),
    ]
